### ISSUE TITLE
DoodleActivity的315行的mSize没做空检查，在移动的时候会crash

### ISSUE THREAD

**Issue by saltwater2233** [1993hzw/Doodle#15]
2019-02-15 10:49:06.521 20992-20992/cn.hzw.doodledemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.hzw.doodledemo, PID: 20992
    java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
        at cn.hzw.doodle.DoodleActivity$2.onSelectedItem(DoodleActivity.java:315)
        at cn.hzw.doodle.DoodleOnTouchGestureListener.onSingleTapUp(DoodleOnTouchGestureListener.java:269)
        at cn.forward.androids.TouchGestureDetector$OnTouchGestureListenerProxy.onSingleTapUp(TouchGestureDetector.java:165)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:640)
        at cn.forward.androids.TouchGestureDetector.onTouchEvent(TouchGestureDetector.java:86)
        at cn.hzw.doodle.DoodleView$DoodleViewInner.onTouchEvent(DoodleView.java:1073)
        at cn.hzw.doodle.DoodleView.dispatchTouchEvent(DoodleView.java:185)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2963)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3356)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
        at android.view.View.dispatchPointerEvent(View.java:11975)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4871)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4682)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4213)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4266)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4232)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4359)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4240)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4416)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4213)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4266)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4232)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4240)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4213)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6780)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6752)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6713)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6888)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:253)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:331)
        at android.os.Looper.loop(Looper.java:149)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by 1993hzw** [comment]
已修复，谢谢反馈！
