### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e5f2cdd

### ISSUE THREAD

**Issue by MyWdq** [1993hzw/Doodle#72]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e5f2cdd
at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55)
at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:78)
at cn.hzw.doodle.DoodleView$b.a(DoodleView.java:9)
at cn.hzw.doodle.DoodleView$b.onDraw(DoodleView.java:5)
at android.view.View.draw(View.java:19384)
at android.view.View.updateDisplayListIfDirty(View.java:18320)

**Comment by anjiemo** [comment]
可以检查一下是否有在 onSaved 回调里调用 callback.run() 回调

**Comment by anjiemo** [comment]
还有一点就是，在回调 callback.run() 后再次保存涂鸦时会没有 onSaved 的回调，需要在源码 save 方法了里的做如下改动

将原来的代码

``` kotlin

            @Override
            protected void onPostExecute(Bitmap bitmap) {
                mDoodleListener.onSaved(DodlView.this, bitmap, new Runnable() {
                    @Override
                    public void run() {
                        if (mOptimizeDrawing) {
                            refreshDoodleBitmap(false);
                        }
                        refresh();
                    }
                });
            }

```

改为

``` kotlin

            @Override
            protected void onPostExecute(Bitmap bitmap) {
                mDoodleListener.onSaved(DodlView.this, bitmap, new Runnable() {
                    @Override
                    public void run() {
                        if (mOptimizeDrawing) {
                            refreshDoodleBitmap(false);
                        }
                        refresh();
                        mIsSaving = false;
                    }
                });
            }

```
